### ISSUE TITLE
failed to build LuaSnip via Lazy.nvim

### ISSUE THREAD

**Issue by AymenSakouhi** [L3MON4D3/LuaSnip#1286]
I have this issue on windows after I tried to install my own setup for Lazyvim.
error
```bash
 process_begin: CreateProcess(NULL, uname, ...) failed.
        Makefile:37: pipe: No error
        process_begin: CreateProcess(NULL, pwd, ...) failed.
        Makefile:49: pipe: No such file or directory
        process_begin: CreateProcess(NULL, pwd, ...) failed.
        Makefile:50: pipe: No such file or directory
        git submodule init
        git submodule update
        C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe "CC=cc" "INCLUDE_DIR=-I'/deps/lua51_include/'" LDLIBS="" -C "deps/jsregexp"
        make[1]: Entering directory 'C:/Users/sakou/AppData/Local/nvim-data/lazy/LuaSnip/deps/jsregexp'
        cc -I'/deps/lua51_include/' -O2 -fPIC -c jsregexp.c -o jsregexp.o
        process_begin: CreateProcess(NULL, cc -I/deps/lua51_include/ -O2 -fPIC -c jsregexp.c -o jsregexp.o, ...) failed.
        make (e=2): The system cannot find the file specified.
        make[1]: *** [Makefile:20: jsregexp.o] Error 2
        make[1]: Leaving directory 'C:/Users/sakou/AppData/Local/nvim-data/lazy/LuaSnip/deps/jsregexp'
        make: *** [Makefile:49: jsregexp] Error 2
```
Anyone facing the same issue?

```lua
return {
	"hrsh7th/nvim-cmp",
	event = "InsertEnter",
	dependencies = {
		"hrsh7th/cmp-buffer", -- source for text in buffer
		"hrsh7th/cmp-path", -- source for file system paths
		{
			"L3MON4D3/LuaSnip",
			-- follow latest release.
			version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
			-- install jsregexp (optional!).
			build = "make install_jsregexp",
		},
		"saadparwaiz1/cmp_luasnip", -- for autocompletion
		"rafamadriz/friendly-snippets", -- useful snippets
		"onsails/lspkind.nvim", -- vs-code like pictograms
	},
	config = function()
		local cmp = require("cmp")

		local luasnip = require("luasnip")

		local lspkind = require("lspkind")

		-- loads vscode style snippets from installed plugins (e.g. friendly-snippets)
		require("luasnip.loaders.from_vscode").lazy_load()

		cmp.setup({
			completion = {
				completeopt = "menu,menuone,preview,noselect",
			},
			snippet = { -- configure how nvim-cmp interacts with snippet engine
				expand = function(args)
					luasnip.lsp_expand(args.body)
				end,
			},
			mapping = cmp.mapping.preset.insert({
				["<C-k>"] = cmp.mapping.select_prev_item(), -- previous suggestion
				["<C-j>"] = cmp.mapping.select_next_item(), -- next suggestion
				["<C-b>"] = cmp.mapping.scroll_docs(-4),
				["<C-f>"] = cmp.mapping.scroll_docs(4),
				["<C-Space>"] = cmp.mapping.complete(), -- show completion suggestions
				["<C-e>"] = cmp.mapping.abort(), -- close completion window
				["<CR>"] = cmp.mapping.confirm({ select = false }),
			}),
			-- sources for autocompletion
			sources = cmp.config.sources({
				{ name = "nvim_lsp" },
				{ name = "luasnip" }, -- snippets
				{ name = "buffer" }, -- text within current buffer
				{ name = "path" }, -- file system paths
			}),

			-- configure lspkind for vs-code like pictograms in completion menu
			formatting = {
				format = lspkind.cmp_format({
					maxwidth = 50,
					ellipsis_char = "...",
				}),
			},
		})
	end,
}
```

![image](https://github.com/user-attachments/assets/33aed7e5-f14d-4f34-bd07-4607dfa97376)

**Comment by AymenSakouhi** [comment]
After a little bit of research,
Here is my solution:
Sharing first the result:
![image](https://github.com/user-attachments/assets/029025ba-a6bb-47f5-9e79-b833689df687)

---
Now how I did it
First I installed MSYS2
then you need to make sure it is installed properly.
Maybe run you few commands to make sure that gcc, cc are installed. ```which gcc``` ```which cc``` is okay.
if not, run ```pacman -S base-devel``` and add the MSYS2 tools installed to your path.
How is that?
1. Open PowerShell as Administrator.
2. Run the following commands to add the paths temporarily for the current session:
```bash 
$env:Path += ";C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\msys64\mingw32\bin"
```
or permanently:
```bash 
$env:Path += [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)
```
then close powershell and reopen and then ```make --version```
that should work
Now restart nvim and redo
```
nvim command: Lazy build LuaSnip
```
if that didn't work
go to  ~\AppData\Local\nvim-data\lazy\LuaSnip
and do a make command there. 
it will build normally and when you relaunch nvim.
try :checkhealth for making sure LuaSnip is working
--
hope this helps...

**Comment by leiserfg** [comment]
Most of the errors of building jsregex happen in windows, why don't we ship a pre build one for them? Windows has fewer ABI variants.

**Comment by AymenSakouhi** [comment]
@leiserfg that's a good idea, would be great to tweak some of the makefile's to use cc=gcc or some pre-requirement based on OS.

**Comment by xudyang1** [comment]
The jsregexp installation on Windows bug should be fixed by #1282. Current solution is to call `make install_jsregexp CC=gcc` and make sure sh.exe can be found in PATH.

**Comment by justicenyaga** [comment]
hey @xudyang1 , could you help figure out why my make install is not working. I'm getting the following error

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/cd1170bb-dac7-4641-925c-449be2b24892" />

but have the lauxlib.h file in deps/lua51_include

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/36059df2-787a-4b7d-a612-4d8b75f0e787" />

**Comment by xudyang1** [comment]
@justicenyaga  please try the latest commit.

**Comment by justicenyaga** [comment]
Hi @xudyang1, after testing the latest commit, `jsregexp` builds without any issues. However, the error still occurs on the latest release, so it seems the fix isn't included there yet.

**Comment by xudyang1** [comment]
@justicenyaga  you can open a discussion and post your `luasnip` configuration so that we can discuss it further.
